name: Prepare Environment
description: Prepare the macOS build environment.
inputs:
  ref:
    description: If set, the ref to checkout.
  install_test_deps:
    description: If true, dependencies needed for running tests will be installed.
  install_release_deps:
    description: If true, dependencies needed for building release artifacts will be installed.

runs:
  using: composite
  steps:
    - name: Make GitHub token available
      shell: bash
      run: echo "GH_TOKEN=${{ github.token }}" >> "$GITHUB_ENV"

    - name: Determine repository root
      id: repo-root
      shell: bash
      run: |
        REPO_ROOT=$(cd "${{ github.action_path }}/../../.." && pwd)
        echo "path=$REPO_ROOT" >> "$GITHUB_OUTPUT"

    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
      with:
        key: macos-arm64
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@dc19f1e48450eefe5a29b8da6c6b00a87d730b37
      env:
        BINSTALL_VERSION: 1.14.4

    - name: Install dependencies
      shell: bash
      run: |
        cd "${{ steps.repo-root.outputs.path }}"
        if ${{ inputs.install_release_deps == 'true' }}; then
          ./script/install_cargo_release_deps
        else
          ./script/install_cargo_build_deps
        fi

    - name: Install test dependencies
      if: ${{ inputs.install_test_deps == 'true' }}
      shell: bash
      run: |
        brew install fish bash || true

    - name: Install protoc
      id: install_protoc
      continue-on-error: true
      uses: arduino/setup-protoc@f4d589e4bdf2cc4829fe24f73d894d8f8194c0bf
      with:
        version: "31.1"

    - name: Install protoc fallback
      if: ${{ steps.install_protoc.outcome == 'failure' }}
      shell: bash
      run: |
        brew install protobuf
