[package]
name = "remote_server"
version = "0.1.0"
edition = "2021"
authors = ["Warply Team <dev@warply.local>"]
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
command.workspace = true
dashmap.workspace = true
futures.workspace = true
futures-lite.workspace = true
log.workspace = true
prost.workspace = true
repo_metadata.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
warp_core.workspace = true
warp_util.workspace = true
warpui.workspace = true
async-io.workspace = true
async-process.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["compat"] }

[build-dependencies]
prost-build.workspace = true
