[package]
name = "watcher"
version = "0.1.0"
edition = "2021"
authors = ["Warply Team <dev@warply.local>"]
publish.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
warpui.workspace = true
log.workspace = true
anyhow.workspace = true
notify-debouncer-full.workspace = true
futures.workspace = true
