[package]
name = "ai"
version = "0.1.0"
edition = "2021"
publish.workspace = true
license.workspace = true

[features]
default = ["local_fs"]
jemalloc = []
local_fs = []
test-util = []

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
async-fs.workspace = true
async-trait.workspace = true
arborium.workspace = true
base16ct = "0.2.0"
bincode.workspace = true
bytes.workspace = true
cfg-if.workspace = true
chrono.workspace = true
computer_use.workspace = true
derivative.workspace = true
dirs.workspace = true
dunce.workspace = true
futures.workspace = true
generic-array = "0.14.7"
ignore = "0.4.23"
instant.workspace = true
itertools.workspace = true
languages.workspace = true
lazy_static.workspace = true
line-span = "0.1.5"
log.workspace = true
nix.workspace = true
notify-debouncer-full.workspace = true
persistence.workspace = true
priority-queue = "2.3.1"
prost-types.workspace = true
rayon.workspace = true
regex.workspace = true
repo_metadata.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2 = "0.10.8"
shellexpand.workspace = true
string-offset.workspace = true
streaming-iterator.workspace = true
strsim.workspace = true
strum.workspace = true
strum_macros.workspace = true
syntax_tree.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
typed-path.workspace = true
unicode-width.workspace = true
uuid.workspace = true
warp_core.workspace = true
warp_terminal.workspace = true
warp_util.workspace = true
watcher.workspace = true
warpui.workspace = true

[dev-dependencies]
filetime = "0.2.25"
tempfile.workspace = true
virtual-fs.workspace = true
warp_core = { workspace = true, features = ["test-util"] }
