[package]
authors = ["Warply Open Source"]
default-run = "warply"
description = "The local-first terminal with ACP agent support"
edition = "2021"
autobins = false
name = "warp"
version = "0.1.0"
publish.workspace = true
license.workspace = true

[lib]
name = "warp"
path = "src/lib.rs"

[[bin]]
name = "warply"
path = "src/bin/oss.rs"
test = false

[[bin]]
name = "generate_settings_schema"
path = "src/bin/generate_settings_schema.rs"
test = false

[dependencies]
addr = "0.15.6"
agent-client-protocol.workspace = true
agent-client-protocol-tokio.workspace = true
ai.workspace = true
alphanumeric-sort = "1.5.7"
anyhow.workspace = true
arrayvec.workspace = true
asset_cache.workspace = true
asset_macro.workspace = true
async-broadcast.workspace = true
async-channel.workspace = true
async-compat.workspace = true
async-fs.workspace = true
async-recursion.workspace = true
async-stream.workspace = true
async-trait.workspace = true
base64.workspace = true
bimap = "0.6.2"
bincode.workspace = true
bitflags.workspace = true
bitflags-serde-legacy.workspace = true
blocking.workspace = true
bounded-vec-deque = "0.1"
bytecount = "0.6.9"
bytes.workspace = true
byte-unit = "5.1.4"
cfg-if.workspace = true
chrono.workspace = true
clap.workspace = true
command = { workspace = true }
command-corrections.workspace = true
command-signatures-v2 = { workspace = true, optional = true }
computer_use.workspace = true
crc.workspace = true
content_inspector = "0.2.4"
concat-idents.workspace = true
csv = "1.3.1"
dashmap.workspace = true
deltae = "0.3.1"
derivative.workspace = true
dhat = { version = "0.3.2", optional = true }
diesel = { workspace = true, features = ["sqlite", "chrono"] }
difflib = { git = "https://github.com/warpdotdev/difflib.git", rev = "114177e7d8e1f8017baca397f943e11644b14d63" }
directories.workspace = true
dirs.workspace = true
dunce.workspace = true
embed_plist = "1.2"
enclose = "1.1.8"
enum-iterator.workspace = true
event-listener = "5.4.0"
field_mask.workspace = true
flate2 = "1.0.17"
float-cmp.workspace = true
futures-lite.workspace = true
futures-util.workspace = true
futures.workspace = true
fuzzy_match.workspace = true
getset.workspace = true
handlebars.workspace = true
hex.workspace = true
http.workspace = true
http_client.workspace = true
image.workspace = true
infer = "0.19.0"
jaq-json.workspace = true
jaq-all.workspace = true
jemalloc_pprof = { version = "0.8.1", optional = true, features = [
    "symbolize",
] }
lsp-types = "0.97.0"
indexmap = { version = "2.0.2", features = ["serde"] }
input_classifier.workspace = true
instant.workspace = true
ipc.workspace = true
itertools.workspace = true
kmeans_colors = { version = "0.5", default-features = false, features = [
    "palette_color",
] }
lazy_static.workspace = true
libc.workspace = true
line-ending.workspace = true
log.workspace = true
lsp.workspace = true
warp_logging.workspace = true
lz4_flex = "0.11"
markdown_parser.workspace = true
memchr.workspace = true
memo-map.workspace = true
mermaid_to_svg.workspace = true
num-traits.workspace = true
num_cpus = "1.13.0"
once_cell.workspace = true
ordered-float.workspace = true
os_info = { version = "3.7.0", default-features = false }
palette = { version = "0.6.0", default-features = false, features = ["std"] }
parking_lot = { version = "0.12.1", features = ["serde"] }
paste = "1.0"
pathfinder_color = "0.5.0"
pathfinder_geometry.workspace = true
persistence.workspace = true
pin-project.workspace = true
plist = "1"
pprof = { workspace = true, optional = true, features = [
    "protobuf-codec",
    "frame-pointer",
] }
prost.workspace = true
prost-types.workspace = true
rand.workspace = true
rangemap.workspace = true
rayon.workspace = true
regex-automata = "0.4.6"
regex.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
inventory = "0.3"
schemars = "1"
serde.workspace = true
serde_bytes.workspace = true
serde-bytes-repr.workspace = true
serde_json.workspace = true
serde_regex = "1.1.0"
serde_urlencoded.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
settings.workspace = true
settings_value = { workspace = true, features = ["derive"] }
sha2.workspace = true
shellexpand.workspace = true
shell-words = "1.1.0"
shlex = "1.3.0"
siphasher = "0.3.11"
similar.workspace = true
simple_logger.workspace = true
smallvec.workspace = true
smol_str.workspace = true
static_assertions.workspace = true
string-offset.workspace = true
sum_tree.workspace = true
tabwriter = "1.4"
tempfile.workspace = true
thiserror.workspace = true
thousands = "0.2.0"
tikv-jemallocator = { version = "0.6", optional = true, features = [
    "override_allocator_on_supported_platforms",
] }
toml = "0.8.13"
toml_edit.workspace = true
tracing.workspace = true
ui_components.workspace = true
unicase = "2.7.0"
unicode-general-category.workspace = true
unicode-width.workspace = true
unindent = "0.1.7"
url = { workspace = true, features = ["serde"] }
urlocator.workspace = true
uuid.workspace = true
warp_cli.workspace = true
validator = "0.19.0"
variant_count = "1.1.0"
vec1.workspace = true
version-compare.workspace = true
vte.workspace = true
walkdir.workspace = true
warp-workflows.workspace = true
warp_completer.workspace = true
warp_core.workspace = true
warp_editor.workspace = true
warp_js = { workspace = true, optional = true }
local_object_model.workspace = true
warp_util.workspace = true
warpui = { workspace = true, features = ["schema_gen", "settings_value"] }
warpui_extras = { workspace = true, features = ["default", "user_preferences-toml"] }
syntax_tree.workspace = true
languages.workspace = true
warp_terminal.workspace = true
natural_language_detection.workspace = true
aho-corasick = "1.1.3"
strum.workspace = true
strum_macros.workspace = true
reqwest-eventsource = { workspace = true }
lasso.workspace = true
counter = "0.6.0"
typed-path.workspace = true
urlencoding = "2.1.3"
mime_guess = "2.0"
remote_server.workspace = true
repo_metadata.workspace = true
vim.workspace = true
warp_ripgrep.workspace = true

block.workspace = true
cocoa.workspace = true
core-foundation.workspace = true
mach2 = "0.5"
objc.workspace = true
objc2-foundation = { workspace = true, features = ["NSBundle"] }
permissions = "0.4.1"
security-framework-sys = "2.0.0"
cvt = "0.1.1"
signal-hook = "0.3.17"
signal-hook-mio = { version = "0.2.4", features = ["support-v1_0"] }
nix = { workspace = true, features = [
    "fs",
    "hostname",
    "resource",
    "signal",
    "socket",
    "term",
    "uio",
    "user",
    "mman",
] }

async-io.workspace = true
axum.workspace = true
comfy-table = "7.1.4"
inquire = "0.9.1"
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
env_logger.workspace = true
git2 = { version = "0.20.4", default-features = false, features = [
    "vendored-libgit2",
] }
http_server.workspace = true
hyper.workspace = true
libsqlite3-sys = { version = "0.33.0", features = ["bundled"] }
mio = { version = "1.1.1", features = ["os-poll", "os-ext"] }
tokio.workspace = true
tokio-util.workspace = true

notify-debouncer-full.workspace = true
rquickjs = { workspace = true, optional = true }
rustls.workspace = true
syntect = "5.0"
sysinfo.workspace = true
warp-command-signatures = { workspace = true, features = ["embed-signatures"] }
is_executable = "1.0.1"
gethostname = "1.1.0"
watcher.workspace = true
warp_files.workspace = true
tantivy = "0.26.0"

[dev-dependencies]
ai = { workspace = true, features = ["test-util"] }
async-process.workspace = true
jsonschema = { workspace = true, default-features = false }
async-executor = "1.5.1"
command = { workspace = true, features = ["test-util"] }
ctor = "0.1.18"
http_client = { workspace = true, features = ["test-util"] }
mockall = "0.13.1"
mockito.workspace = true
serial_test = "0.8.0"
sum_tree = { workspace = true, features = ["test-util"] }
virtual-fs.workspace = true
warp_completer = { workspace = true, features = ["test-util"] }
warp_core = { workspace = true, features = ["test-util"] }
warp_editor = { workspace = true, features = ["test-util"] }
local_object_model = { workspace = true, features = ["test-util"] }
warp_terminal = { workspace = true, features = ["test-util"] }
warpui = { workspace = true, features = ["test-util"] }
warpui_extras = { workspace = true, features = ["test-util"] }
warp_files = { workspace = true, features = ["test-util"] }
repo_metadata = { workspace = true, features = ["test-util"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process", "time"] }

[build-dependencies]
anyhow = "1.0"
cc = "1.0"
prost-build.workspace = true
sha2.workspace = true
tempfile.workspace = true
walkdir = "2.3.2"
warp_util.workspace = true

# Note that we support channel-specific enables for these features
[features]
changelog = []
completions_v2 = [
    "plugin_host",
    "warp_completer/v2",
    "dep:command-signatures-v2",
]
default = [
    "render_continuous_block_selections_with_single_border",
    "shell_selector",
    "minimalist_ui",
    "full_screen_zen_mode",
    "workflow_aliases",
    "ligatures",
    "dynamic_workflow_enums",
    "rect_selection",
    "command_correction_key",
    "kitty_images",
    "command_palette_file_search",
    "tab_close_button_on_left",
    "code_find_replace",
    "tabbed_editor_view",
    "undo_closed_panes",
    "revert_diff_hunk",
    "vim_code_editor",
    "expand_edit_to_pane",
    "ui_zoom",
    "classic_completions",
    "force_classic_completions",
    "pluggable_notifications",
    "global_search",
    "inline_slash_commands",
    "inline_history_menu",
    "new_tab_styling",
    "richtext_multiselect",
    "incremental_auto_reload",
    "kitty_keyboard_protocol",
    "inline_menu_headers",
    "markdown_tables",
    "markdown_mermaid",
    "configurable_toolbar",
    "vertical_tabs",
    "tab_configs",
    "directory_tab_colors",
]
# Enable this feature to automatically perform heap profiling.  NOTE: This will
# substantially slow down program execution.
dhat_heap_profiling = ["dep:dhat"]
dynamic_workflow_enums = []
editable_markdown_mermaid = []
drag_tabs_to_windows = []
extern_plist = []
fast_dev = []
full_screen_zen_mode = []
# This feature is enabled in graphical builds of Warply, and groups together other features
# that are not needed in headless builds. Because Cargo features are additive, the default
# feature set is for a minimal build of Warply, and we add on GUI-specific features here.
# For the most part, including GUI code in headless builds is fine; the main use case is
# for things that pull in external dependencies.
gui = []
welcome_tab = []
inline_slash_commands = []

# Enable this feature to track heap usage and automatically produce a heap
# profile report when app memory usage exceeds a 10GB threshold.
#
# Enabled on Warply development builds by default.
heap_usage_tracking = ["jemalloc_pprof"]
in_band_generators_ssh = []
jemalloc = ["dep:tikv-jemallocator", "ai/jemalloc"]
jemalloc_with_profiling = ["jemalloc", "tikv-jemallocator/profiling"]
jemalloc_auto_heap_profiling = ["jemalloc_with_profiling"]
jemalloc_pprof = ["jemalloc_with_profiling", "dep:jemalloc_pprof"]
kitty_images = []
kitty_keyboard_protocol = []
ligatures = []
# This feature is enabled in build.rs when compiling for platforms which
# support having a local tty/shell session.  It can be used to conditionally
# include dependencies that should only exist in such environments.
local_tty = []
# This feature is enabled in build.rs when compiling for platforms which
# have APIs for interacting with a local filesystem.  It can be used to
# conditionally include dependencies that should only exist in such
# environments.
local_fs = [
    "ai/local_fs",
    "lsp/local_fs",
    "persistence/local_fs",
    "repo_metadata/local_fs",
    "warp_core/local_fs",
]
markdown_tables = []
markdown_mermaid = []
# Fix for cursor reflow bug during window resize, from Alacritty resizing logic.
resize_fix = []
pluggable_notifications = []
# This feature enables plugin support in Warply. Note that its typically checked
# directly, rather than via the `FeatureFlag` enum, because its value is
# required early in the app lifecycle prior to `FeatureFlag` initialization.
plugin_host = ["dep:rquickjs", "dep:warp_js", "warp_cli/plugin_host"]
# Enable this feature to automatically perform CPU profiling via pprof.  The
# generated profile will be written to profile.pb in the current directory.
# NOTE: This may slow down program execution.
pprof_cpu_profiling = ["dep:pprof"]
quake_mode = []
recording_mode = []
# This feature should only be enabled when building a release bundle with
# the bundle script, and can be used to conditionally enable functionality
# accordingly.
release_bundle = ["rust-embed/debug-embed", "warp_core/release_bundle"]
render_continuous_block_selections_with_single_border = []
rich_history = []
richtext_multiselect = []
runtime_feature_flags = []
selectable_prompt = []
sequential_storage = []
# This feature should only be enabled when building a self-contained binary with the bundle script.
standalone = []
system_theme = []
tab_close_button_on_left = []
toggle_bootstrap_block = []
# Feature enabled only when app is compiled for integration tests.
integration_tests = [
    "warp_cli/integration_tests",
    "warpui/defer_scene_build",
    "warpui/integration_tests",
    "warpui/test-util",
    "warp_core/integration_tests",
]
traces = []
workflow_aliases = []
rect_selection = []
alacritty_settings_import = []
shell_selector = []
minimalist_ui = []
ime_marked_text = []
iterm_images = []
command_correction_key = []
use_tantivy_search = []
nld_onnx_model = ["input_classifier/onnx_candle"]
code_find_replace = []
command_palette_file_search = []
expand_edit_to_pane = []
tabbed_editor_view = []
projects = []
vim_code_editor = []
undo_closed_panes = []
revert_diff_hunk = []
ui_zoom = []
global_search = []
classic_completions = []
force_classic_completions = []
inline_history_menu = []
new_tab_styling = []
incremental_auto_reload = []
inline_menu_headers = []
directory_tab_colors = []
vertical_tabs = []
vertical_tabs_summary_mode = []
tab_configs = []
configurable_toolbar = []

[package.metadata.bundle.bin.warply]
category = "public.app-category.developer-tools"
copyright = "© 2026, Warply Open Source"
identifier = "dev.zhangyu1818.warply"
name = "Warply"
icon = ["channels/oss/icon/no-padding/512x512.png", "channels/oss/icon/no-padding/icon.ico"]
short_description = "The open-source, local-first terminal with ACP agent support."

[package.metadata.cargo-udeps.ignore]
normal = ["embed_plist"]
