[package]
name = "warp_logging"
edition = "2024"
description = "Warp logging configuration"
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cfg-if.workspace = true
env_logger.workspace = true
log.workspace = true
warp_core.workspace = true
dirs.workspace = true
