#!/usr/bin/env bash

for arg in "$@"; do
  case "$arg" in
    -y|--yes) export WARPLY_SKIP_SUDO_PROMPT=1 ;;
  esac
done

OS_TYPE="$(uname -s)"

if [[ "$OS_TYPE" = "Darwin" ]]; then
  ./script/macos/bootstrap "$@"
else
  echo "Warply bootstrap is supported only on macOS." >&2
  exit 1
fi
