#!/bin/bash

set -e

if command -v cargo-bundle >/dev/null 2>&1; then
    echo "cargo-bundle already exists, not installing."
    exit 0
fi

cargo install cargo-bundle --git=https://github.com/burtonageo/cargo-bundle --rev ae4c76e92c08774bf54ff077b1c52e3d1cd6c16d
