[package]
name = "warpui"
version = "0.0.0"
edition = "2021"
authors.workspace = true
publish.workspace = true
license = "MIT"

[features]
# Enabling this feature works around a bug in Metal frame capture by loading
# Metal shaders from the file system instead of from data compiled into the
# binary. The shaders are written to the temp directory during initialization of
# a renderer to enable this, which could slow opening of the first window.
enable-metal-frame-capture = []
# Enables the font-kit rasterizer on Windows.
fontkit-rasterizer = []
traces = ["warpui_core/traces"]
# Feature enabled only when app is compiled for integration tests.
integration_tests = ["warpui_core/integration_tests"]
schema_gen = ["warpui_core/schema_gen"]
settings_value = ["warpui_core/settings_value"]
# Enables utilities for testing.
test-util = ["warpui_core/test-util"]

[dependencies]
async-task.workspace = true
anyhow.workspace = true
cfg-if.workspace = true
dashmap.workspace = true
derive_more.workspace = true
futures.workspace = true
futures-util.workspace = true
instant.workspace = true
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
markdown_parser.workspace = true
num-traits.workspace = true
ordered-float.workspace = true
parking_lot.workspace = true
pathfinder_color.workspace = true
pathfinder_geometry.workspace = true
sum_tree.workspace = true
takecell = "0.1.1"
thiserror.workspace = true
vec1.workspace = true
warpui_core.workspace = true
async-io.workspace = true
ctrlc.workspace = true

[dev-dependencies]
asset_cache.workspace = true
env_logger.workspace = true
futures-timer = "3.0.2"
image = { workspace = true, default-features = false, features = ["png"] }
rust-embed.workspace = true
warpui = { workspace = true, features = ["test-util"] }
warpui_core = { workspace = true, features = ["test-util"] }

[target.'cfg(target_os = "macos")'.dependencies]
block.workspace = true
chrono.workspace = true
cocoa.workspace = true
core-foundation.workspace = true
core-graphics = "0.25.0"
core-text = "21.0.0"
dispatch = "0.2.0"
font-kit.workspace = true
foreign-types = "0.5.0"
libc.workspace = true
metal = "0.33.0"
objc.workspace = true

[target.'cfg(target_os = "macos")'.dev-dependencies]
rand.workspace = true

[build-dependencies]
bindgen = "0.70.1"
cc = { version = "1.0", features = ["parallel"] }
cfg_aliases.workspace = true
