[package]
name = "persistence"
edition = "2024"
authors.workspace = true
publish.workspace = true
license.workspace = true

[features]
default = ["local_fs"]
local_fs = []

[dependencies]
chrono.workspace = true
diesel = { workspace = true, features = [
    "chrono",
    "32-column-tables",
] }
diesel_migrations = "2.2.0"
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
